<?= $this->doctype() ?>
<html lang="<?= LOCALE ?>">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Paweł Mleczko - admin panel')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        ->prependStylesheet($this->basePath('css/inspiration.css'))
        ->prependStylesheet($this->basePath('css/plugins/summernote/summernote-bs3.css'))
        ->prependStylesheet($this->basePath('css/plugins/summernote/summernote.css'))
        ->prependStylesheet($this->basePath('css/plugins/iCheck/custom.css'))
        ->prependStylesheet($this->basePath('css/plugins/ladda/ladda-themeless.min.css'))
        ->prependStylesheet($this->basePath('css/plugins/select2/select2.min.css'))
        ->prependStylesheet($this->basePath('css/plugins/sweetalert/sweetalert.css'))
        ->prependStylesheet($this->basePath('css/plugins/switchery/switchery.css'))
        ->prependStylesheet($this->basePath('css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css'))
        ->prependStylesheet($this->basePath('css/plugins/dataTables/datatables.min.css'))
        ->prependStylesheet($this->basePath('css/plugins/toastr/toastr.min.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/inspinia.js'))
        ->prependFile($this->basePath('js/plugins/summernote/summernote.min.js'))
        ->prependFile($this->basePath('js/plugins/pace/pace.min.js'))
        ->prependFile($this->basePath('js/plugins/i18next/i18next.min.js'))
        ->prependFile($this->basePath('js/plugins/ladda/ladda.jquery.min.js'))
        ->prependFile($this->basePath('js/plugins/ladda/ladda.min.js'))
        ->prependFile($this->basePath('js/plugins/ladda/spin.min.js'))
        ->prependFile($this->basePath('js/plugins/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.tooltip.min.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.time.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.pie.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.resize.js'))
        ->prependFile($this->basePath('js/plugins/flot/jquery.flot.js'))
        ->prependFile($this->basePath('js/plugins/select2/select2.full.min.js'))
        ->prependFile($this->basePath('js/plugins/sweetalert/sweetalert.min.js'))
        ->prependFile($this->basePath('js/plugins/switchery/switchery.js'))
        ->prependFile($this->basePath('js/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js'))
        ->prependFile($this->basePath('js/plugins/dataTables/responsive.js'))
        ->prependFile($this->basePath('js/plugins/dataTables/datatables.min.js'))
        ->prependFile($this->basePath('js/plugins/toastr/toastr.min.js'))
        ->prependFile($this->basePath('js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('js/plugins/metisMenu/jquery.metisMenu.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.1.min.js'))
    ?>
    <script>
        function makeToast(title, content, state) {
            toastr.options = {
                closeButton: true,
                progressBar: true,
                preventDuplicates: true,
                positionClass: 'toast-top-right',
                onclick: null
            };

            switch (state) {
                case 0: toastr.error(content, title); break;
                case 1: toastr.warning(content, title); break;
                case 2: toastr.info(content, title); break;
                case 3: toastr.success(content, title); break;
                case '0': toastr.error(content, title); break;
                case '1': toastr.warning(content, title); break;
                case '2': toastr.info(content, title); break;
                case '3': toastr.success(content, title); break;
            }
        }

        function getCookie(cname) {
            var name = cname + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
//            console.log(decodedCookie);
            var ca = decodedCookie.split(';');
            for(var i = 0; i <ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }
        var inter = setInterval(function () {
            var cookie = getCookie('toast');
            var stateC = getCookie('state');
            var title = getCookie('title');
            if (cookie != '') {
                tmpCookie = cookie.split('+');
                cookie = '';
                for (var i = 0; i < tmpCookie.length; i++) {
                    cookie += tmpCookie[i] + ' ';
                }
                makeToast(title, cookie, stateC);
                console.log(cookie);
                clearInterval(inter);
            }
        }, 2000);
    </script>
</head>
<body>
<script>
    <?php $_SESSION['account_count']++; if ($_SESSION['User'] && ($_SESSION['account_count'] == 1 || $_SESSION['account_count'] == 2)): ?>
    makeToast('Sukces', 'Zalogowano jako \<b\><?php echo $_SESSION['User']['name'] ?>\</b\>', 3);
    <?php endif; ?>
</script>
<div id="wrapper" class="i18_links">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><?php echo $_SESSION['User']['name'] ?></strong>
                             </span> <span class="text-muted text-xs block"><?php echo $_SESSION['User']['role'] ?> <b class="caret"></b></span> </span> </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="<?php echo $this->url('auth/logout'); ?>"><?php echo $this->translate("Wyloguj", 'default', LOCALE); ?></a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        IN+
                    </div>
                </li>
                <?= $this->navigation('navigation')->menu()->setMinDepth(0)->setMaxDepth(3)->setUlClass('nav metismenu js-menu')->setPartial('partial/navigation') ?>
            </ul>

        </div>
    </nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0; background-color: #263949;">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" method="post" action="#">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="<?php echo $this->url('auth/logout'); ?>">
                            <i class="fa fa-sign-out"></i> <?php echo $this->translate("Wyloguj", 'default', LOCALE); ?>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <?= $this->content ?>
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2017
            </div>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
<script>
    $.i18n.init({
        resGetPath: 'locales/__lng__.json',
        load: 'unspecific',
        fallbackLng: false,
        lng: 'pl'
    }, function (t){
        $('.i18_links').i18n();
    });
    $(document).ready(function () {

    });
</script>
</body>
</html>
